# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: supportbot
metadata:
  template: azd-init@1.5.0
pipeline:
  provider: azdo
services:
