# Run when commits are pushed to mainline branch
trigger:
  - main
pr: none

jobs:
- deployment: All
  displayName: All
  pool:
    vmImage: ubuntu-latest
  environment: 'supportbot-dev'
  container: mcr.microsoft.com/azure-dev-cli-apps:latest
  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self
          - pwsh: |
              azd config set auth.useAzCliAuth "true"
            displayName: Configure AZD to use AZ CLI authentication
          - task: AzureCLI@2
            displayName: Provision infrastructure
            inputs:
              azureSubscription: $(SERVICE_CONNECTION_NAME)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                azd provision --no-prompt
            env:
              AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
              AZURE_ENV_NAME: $(Environment.Name)
              AZURE_LOCATION: $(AZURE_LOCATION)
              AZURE_RESOURCE_GROUP_NAME: ${AZURE_RESOURCE_GROUP_NAME}