# Run when commits are pushed to mainline branch
trigger:
  - main
pr: none

parameters:
- name: deployRoleAssignments
  displayName: 'Deploy role assignments?'
  type: boolean
  default: false

jobs:
- deployment: All
  displayName: All
  pool:
    vmImage: ubuntu-latest
  environment: 'supportbot-dev'
  container: mcr.microsoft.com/azure-dev-cli-apps:latest
  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self
          - script: |
              sudo apt-get update
              az --version
              az upgrade --y
              az --version
            displayName: Upgrade Azure CLI
          - pwsh: |
              azd config set auth.useAzCliAuth "true"
            displayName: Configure AZD to use Azure CLI authentication
          - task: AzureCLI@2
            displayName: Provision infrastructure
            inputs:
              azureSubscription: $(SERVICE_CONNECTION_NAME)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                azd provision --no-prompt --preview
            env:
              AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
              AZURE_ENV_NAME: $(Environment.Name)
              AZURE_LOCATION: $(AZURE_LOCATION)
              AZURE_RESOURCE_GROUP_NAME: ${AZURE_RESOURCE_GROUP_NAME}
              PRODUCT_NAME: ${PRODUCT_NAME}
              DEPLOY_ROLE_ASSIGNMENTS: ${{ parameters.deployRoleAssignments }}
          - task: AzureCLI@2
            condition: false
            displayName: Azure Dev Deploy
            inputs:
              azureSubscription: $(SERVICE_CONNECTION_NAME)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                azd deploy --no-prompt
            env:
              AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
              AZURE_ENV_NAME: $(Environment.Name)
              AZURE_LOCATION: $(AZURE_LOCATION)
              AZURE_RESOURCE_GROUP_NAME: ${AZURE_RESOURCE_GROUP_NAME}
              PRODUCT_NAME: ${PRODUCT_NAME}
              DEPLOY_ROLE_ASSIGNMENTS: ${{ parameters.deployRoleAssignments }}