steps:
  - task: Cache@2
    inputs:
      key: pnpm | "$(Agent.OS)" | pnpm-lock.yaml
      path: $(pnpm_config_cache)
    displayName: 'Cache PNPM'

  - script: |
      corepack enable
      corepack prepare pnpm@latest-8 --activate
      pnpm config set store-dir $(pnpm_config_cache)
      pnpm install
    displayName: 'Install Dependencies'