steps:
  - task: UseNode@1
    inputs:
      version: '18.17'
    displayName: 'Install Node.js'

  - task: Cache@2
    inputs:
      key: pnpm | "$(Agent.OS)" | pnpm-lock.yaml
      path: $(pnpm_config_cache)
    displayName: 'Cache PNPM'

  - script: |
      corepack enable
      pnpm config set store-dir $(pnpm_config_cache)
      pnpm install
    displayName: 'Install Dependencies'