steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      addToPath: true
      architecture: 'x64'
    displayName: 'Use Python $(python.version)'
    
  - script: |
      python -m pip install --upgrade pip
      pip install pipenv
      pipenv install --dev
    displayName: 'Install Dependencies'